# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

bazel_dep(name = "score_baselibs", version = "0.2.12")
single_version_override(
    module_name = "score_baselibs",
    patch_strip = 1,
    patches = [
        "//patches/score/baselibs:0001-fix-openssl-build-for-autosd.patch",
        "//patches/score/baselibs:0002-fix-add-non_null_from_ref.patch",
        "//patches/score/baselibs:0003-fix-test_from_utf8_error_debug-test.patch",
        "//patches/score/baselibs:0004-fix-implement-Default-manually-for-CStringViewStorag.patch",
        "//patches/score/baselibs:0005-fix-bind-format_args-value-to-a-local-to-avoid-dropp.patch",
        "//patches/score/baselibs:0006-fix-replace-unstable-std-APIs-is_multiple_of-inheren.patch",
        "//patches/score/baselibs:0007-fix-use-stable-core-str-from_utf8_unchecked-in-ffi.patch",
    ],
    version = "0.2.12",
)

bazel_dep(name = "score_logging", version = "0.2.4")
single_version_override(
    module_name = "score_logging",
    patch_strip = 1,
    patches = [
        "//patches/score/logging:0001-fix-use-stable-core-str-from_utf8-instead-of-unstabl.patch",
    ],
    version = "0.2.4",
)

bazel_dep(name = "score_persistency", version = "0.3.5")
bazel_dep(name = "score_lifecycle", version = "0.6.1")
bazel_dep(name = "score_communication", version = "0.4.0")
single_version_override(
    module_name = "score_communication",
    patch_strip = 1,
    patches = [
        "//patches/score/communication:0001-Fix-tag-api_surface_test-as-manual.patch",
    ],
    version = "0.4.0",
)

bazel_dep(name = "score_time", version = "0.0.2")
#git_override(
#    module_name = "score_time",
#    branch = "main",
#    patch_strip = 1,
#    patches = [],
#    remote = "https://github.com/eclipse-score/inc_time.git",
#)

bazel_dep(name = "score_config_management", version = "0.2.0")
single_version_override(
    module_name = "score_config_management",
    patch_strip = 1,
    patches = [
        "//patches/score/config_management:0001-fix-MODULE.bazel-file.patch",
    ],
)
